# Generated by Django 4.2.4 on 2023-10-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_petshop_reservadebanho_petshop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadebanho',
            name='petshop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReservaDeBanho', to='reserva.petshop'),
        ),
    ]
