# Generated by Django 4.2.4 on 2023-11-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_reservadebanho_petshop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservadebanho',
            name='petshop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReservaDeBanho', to='reserva.petshop', verbose_name='Unidade'),
        ),
    ]
