# Generated by Django 4.2.4 on 2023-11-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_alter_petshop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservadebanho',
            options={'ordering': ['id'], 'verbose_name': 'Formulário de Reserva de Banho', 'verbose_name_plural': 'Formulários de Reservas de Banhos'},
        ),
        migrations.AlterField(
            model_name='reservadebanho',
            name='petshop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reserva.petshop', verbose_name='Unidade'),
        ),
    ]
